### PR TITLE
[VIT-701] make end_date optional

### PR DESCRIPTION
**Pull request by gabrieleangeletti**

### CODE REVIEW

**Review by maitham — COMMENTED** [review]
Does this pass in undefined? if you make a request with end_date as optional. Whats the effect our side? if an undefined gets passed in?

**Comment by gabrieleangeletti** [comment]
It passes undefined, which is ignored by axios (https://github.com/axios/axios/issues/1139, https://github.com/axios/axios/blob/638804aa2c16e1dfaa5e96e68368c0981048c4c4/lib/helpers/buildURL.js#L38) by not setting it in the params object.

**Review by maitham — APPROVED** [review]

**Comment by jawn-ha** [comment]
Is there any progress?

**Comment by RuiAAPeres** [comment]
@jawn-ha the PR Is merged. 😄

**Pull request merged**
